Repository Ecell-NITS/e-cell-website-22, pull requests merged in 2023-03, with the labels that each got.

#78 FIX:issue 77
  src/Data/TestimonialData.jsx
  src/components/EventsPage/AllEvents.jsx
  src/components/EventsPage/PastEvents.jsx
  src/components/EventsPage/UpcomingEvents.jsx
  src/components/Home/Testimonial/Testimonial.jsx
  src/components/ResourceModal/BooksSummary.jsx
  src/components/ResourceModal/PodcastSummary.jsx
Labels: pls merge

#79 FIX: Responsive and Transition
  src/components/Home/Events/Events.css
  src/components/Home/Events/Events.jsx
Labels: pls merge

#82 UPD:An attempt to Intersection observer API to lazy load img, transition fix in Team, migrate to cloudinary
  public/ecell-logo-bw2.png
  public/index.html
  src/App.css
  src/Data/Developers.json
  src/Data/TestimonialData.jsx
  src/assets/HERO SECTION-compressed.jpg
  src/assets/Team/teamhero.jpeg
  src/assets/collaboration/CocoCola-compressed.png
  src/assets/collaboration/Cognizant_Mangalore_Feb7_2020_2_1581097237290_1581335758668-compressed.jpg
  src/assets/collaboration/IEEE-compressed.jpg
  src/assets/collaboration/PNB-compressed.jpg
  src/assets/collaboration/RuPay.png
  src/assets/collaboration/Unacademy-compressed.jpg
  src/assets/collaboration/Vedantu-compressed.jpg
  src/assets/ecell-logo-bw2.png
  src/assets/testimonial/Quote.svg
  src/assets/testimonial/TESTIMONIAL IMAGE.png
  src/assets/testimonial/sivaji.jpg
  src/components/GalleryPage/GalleryCard/GalleryCard.jsx
  src/components/Home/HeroSection_homepage/Hero.css
  src/components/Home/Testimonial/Testimonial.jsx
  src/components/Home/Testimonial/testimonial.css
  src/components/Home/collaboration/Collab.css
  src/components/Home/collaboration/Collaboration.jsx
  src/components/Teampage/CoreTeam/Coreteam1.jsx
  src/components/Teampage/CoreTeam/Coreteam2.jsx
  src/components/Teampage/CoreTeam/Coreteam3.jsx
  src/components/Teampage/Developers/Jundev/Developers.css
  src/components/Teampage/Developers/Jundev/Developers1.jsx
  src/components/Teampage/Developers/Sendev/Developers2.jsx
  src/components/Teampage/Developers/Sendev/SrDevelopers.css
  src/components/Teampage/Faculties/Faculties.jsx
  src/components/shared/Footer/Footer.css
  src/components/shared/Footer/Footer.jsx
  src/components/shared/Navbar/Navbar.jsx
  src/components/shared/Navbar/NavbarTeam.jsx
  src/pages/Gallery/Gallery.css
  src/pages/Team/Team.css
Labels: enhancement, bug fix

#94 ADD:active state in navbar
  src/components/Home/About Us/About_us.css
  src/components/Home/About Us/About_us.jsx
  src/components/shared/Navbar/Navbar.css
  src/components/shared/Navbar/Navbar.jsx
  src/components/shared/Navbar/NavbarTeam.css
  src/components/shared/Navbar/NavbarTeam.jsx
  src/pages/Resources/Resources.css
Labels: enhancement

#95 UPD:hero content
  public/index.html
  src/components/Home/HeroSection_homepage/Hero.css
  src/components/Home/HeroSection_homepage/Hero.jsx
Labels: pls merge
