Repository Ecell-NITS/e-cell-website-22, pull requests merged in 2023-04, with the labels that each got.

#100 Timelineedit
  src/assets/Empressario.png
  src/assets/Innovation.png
  src/assets/Orientation.png
  src/assets/Pre-Incubation.png
  src/assets/Srijan.png
  src/assets/arrow-down.png
  src/assets/arrow-up.png
  src/assets/timeline-bg.png
  src/components/Home/Timeline/Timeline.css
  src/components/Home/Timeline/Timeline.jsx
Labels: enhancement

#104 UPD:update content in event--partially done
  src/Data/EventsData.jsx
  src/components/EventsPage/AllEvents.jsx
  src/components/EventsPage/PastEvents.jsx
  src/components/EventsPage/UpcomingEvents.css
  src/components/EventsPage/UpcomingEvents.jsx
  src/components/ResourceModal/BooksSummary.jsx
  src/components/ResourceModal/PodcastSummary.jsx
Labels: pls merge

#109 UPD : Images and content updated in events
  src/Data/EventsData.jsx
  src/components/EventsPage/AllEvents.jsx
  src/components/EventsPage/UpcomingEvents.css
  src/components/Teampage/CoreTeam/Core.css
  src/components/Teampage/CoreTeam/Coreteam1.jsx
  src/components/Teampage/CoreTeam/Coreteam2.jsx
  src/components/Teampage/CoreTeam/Coreteam3.jsx
Labels: pls merge

#105 UPD: Events Content updated
  src/Data/EventsData.jsx
  src/components/EventsPage/AllEvents.jsx
  src/components/EventsPage/UpcomingEvents.css
  src/components/Teampage/CoreTeam/Core.css
  src/components/Teampage/CoreTeam/Coreteam1.jsx
  src/components/Teampage/CoreTeam/Coreteam2.jsx
  src/components/Teampage/CoreTeam/Coreteam3.jsx
Labels: pls merge

#111 UPD: Core cards resized
  src/components/Home/About Us/About_us.css
  src/components/Home/About Us/About_us.jsx
  src/components/Home/About Us/Card.css
  src/components/Teampage/CoreTeam/Core.css
  src/components/Teampage/CoreTeam/Coreteam2.jsx
Labels: bug fix

#116 ADD: Error page added
  src/Data/Core1.json
  src/Data/Core2.json
  src/assets/404.json
  src/components/Teampage/CoreTeam/Core.css
  src/pages/404/NotFound.jsx
  src/pages/404/notfound.css
Labels: pls merge
